CobeyH/Leora

Assets/Scenes/Level1.unity, Assets/Scenes/Templates.meta, Assets/Scenes/Templates/Basic Template.scenetemplate, Assets/Scenes/Templates/Basic Template.scenetemplate.meta
Simple issue creating a basic scene template for future level expansion.
=> Adding scene template

Assets/Animations/CrossFade_End.anim, Assets/Animations/CrossFade_End.anim.meta, Assets/Animations/CrossFade_Start.anim, Assets/Animations/CrossFade_Start.anim.meta, Assets/Animations/Transition.controller, Assets/Animations/Transition.controller.meta, Assets/Prefabs/LevelLoader.prefab, Assets/Prefabs/LevelLoader.prefab.meta, Assets/Scenes/Level1.unity, Assets/Scenes/Level3.unity, Assets/Scenes/LevelSelector.unity, Assets/Scenes/Templates/Basic Template.scenetemplate, Assets/Scripts/LevelChanger.cs, Assets/Scripts/LevelLoader.cs, Assets/Scripts/LevelLoader.cs.meta, Assets/Scripts/Lights/AutoPlayLevel.cs, Assets/Scripts/Menus/LevelCompleteMenu.cs, Assets/Scripts/Menus/PauseMenu.cs
Creating groundwork for scene transition animations. I centralized the loading of scene so that it's easy to start the transition from anywhere in the code. All level loading should be done using the LevelLoader script now.
=> Scene transitions

Assets/Prefabs/Managers/LevelLoader.prefab, Assets/Scenes/Background.prefab, Assets/Scenes/Levels/Level1.unity, Assets/Scenes/Levels/Level1/Background.prefab
Several parts of the splash screen were broken since we haven't updated it in so long. I removed all the unused colliders and scripts from the lights in that scene. I also added a "Level Loader" component to the scene so that it can load the "Level Selection" screen.
=> Auto play fix

Assets/Prefabs/World/MothFlock.prefab, Assets/Scenes/LevelSelector.unity, Assets/Scenes/Levels/Level1/MothFlock.prefab, Assets/Scripts/Lights/LightAttraction.cs
Fixed the bug where moths fly too fast
resolves #110
=> Moth too fast

Assets/Scripts/Lights/IntensityRange.cs, Assets/Scripts/Lights/LightAttraction.cs, Assets/Scripts/Lights/LightController.cs, Assets/Scripts/Lights/LightLimit.cs, Assets/Scripts/Lights/SparkController.cs
Updating scripts so that lights are actually disabled instead of setting their outer radius to 0.
Resolves #113
=> Fix attraction overvoltage

Assets/Blur Volume Profile.asset, Assets/Prefabs/Level Selection/LevelButton.prefab, Assets/Prefabs/Managers/LevelLoader.prefab, Assets/Prefabs/UI/Menus/UIButton.prefab, Assets/Scenes/LevelSelector.unity, Assets/Scenes/Levels/Level1.unity, Assets/Scenes/Levels/Level1/LevelLoader.prefab, Assets/Scenes/Levels/Level1/PauseMenu.prefab, Assets/Scenes/Levels/Level1/SettingsMenu.prefab, Assets/Scenes/Levels/Level1/UIButton.prefab, Assets/Scenes/Levels/Level2.unity, Assets/Scenes/Levels/Level3/LevelLoader.prefab, Assets/Scenes/Levels/Level4.unity, Assets/Scenes/Levels/Level5.unity, Assets/Scenes/Levels/Level5/LevelLoader.prefab, Assets/Scenes/Levels/Level6.unity, Assets/Scenes/Levels/Level6/LevelLoader.prefab, Assets/Scenes/Levels/Level7.unity, Assets/Scenes/Levels/Level7/LevelLoader.prefab
Many small bug fixes in preparation for user testing.
- Fixed transition screen hiding behind game UI.
- Adding moth particles back to level selection screen.
- Improving hover colour of menu buttons.
- Cleaning up colliders.
=> QA Bug Fixes

Assets/Scenes/Levels/Level6.unity, Assets/Scripts/FrogTongue.cs, Assets/Scripts/Moths/MothLifetime.cs
=> Fixing frog persistent targeting and eating period

Assets/Scripts/LevelButtons.cs
Fixing off-by-issue in the level buttons
=> Fixing level index bug

Assets/Scripts/Lights/LightAttraction.cs
Changing the way the moth light attraction works. Instead of attraction working like a net-force-diagram it instead works like a center-of-mass model. The moths are attracted to a "center of intensity".
Resolves #153
=> Moth equilibrium

Assets/Prefabs/UI/Menus/SettingsMenu.prefab
=> Setting volume slider fix

Assets/Scenes/Levels/Level6.unity, Assets/Scripts/Lights/LightAttraction.cs
Very simple PR adding missing shadows to level 6.
Resolves #170
=> Adding shadow casters to level 6

Assets/Bloom Volume Profile.asset
Universally reduced the bloom to reduce the settings glow and the portals from getting washed out
Resolves #135
=> Reducing bloom

Assets/Scripts/GameProgress/LevelProgressTracker.cs, Assets/Scripts/LevelLoader.cs
Fixed the bug where when a user completes a level, it unlocks 2 levels after that
=> fixed unlocking function

Assets/Prefabs/Managers/GameManager.prefab, Assets/Prefabs/UI/Menus/Canvas.prefab, Assets/Prefabs/UI/Menus/LevelFailedMenu.prefab, Assets/Prefabs/UI/Menus/LevelWonMenu.prefab, Assets/Prefabs/UI/Menus/MenuBase.prefab, Assets/Prefabs/UI/Menus/PauseMenu.prefab, Assets/Prefabs/UI/Menus/SettingsMenu.prefab, Assets/ScriptableObjects.meta, Assets/ScriptableObjects/ToggleMenuChannel.asset, Assets/ScriptableObjects/ToggleMenuChannel.asset.meta, Assets/Scripts/Channels.meta, Assets/Scripts/Channels/MenuEventChannelSO.cs, Assets/Scripts/Channels/MenuEventChannelSO.cs.meta, Assets/Scripts/Channels/VoidEventChannelSO.cs, Assets/Scripts/Channels/VoidEventChannelSO.cs.meta, Assets/Scripts/GameController.cs, Assets/Scripts/Menus/MenuController.cs, Assets/Scripts/Menus/MenuTypes.cs, Assets/Scripts/Menus/MenuTypes.cs.meta, Assets/Scripts/Menus/PauseButton.cs
Converting the pause menu to use scriptable objects and events instead of referenced to other game objects.
=> Scriptable pause

Assets/Prefabs/World/Goal.prefab, Assets/Prefabs/World/MothFlock.prefab
Fixed issue of two flocks of moths get really slow when merge with each other.
=> fixed flocks merging issue

Assets/Sprites/Mossy - FloatingPlatforms.png.meta, Assets/Sprites/Mossy - TileSet.png.meta
Updated physics shapes of tilemap to stop moths getting stuck on them.
Resolves  #207
=> Updating physics shapes

Assets/Prefabs/World/WaspFlock.prefab, Assets/Prefabs/World/WaspFlock.prefab.meta, Assets/Scripts/Moths/Wasp.cs, Assets/Scripts/Moths/Wasp.cs.meta
Adding a new prefab variant for moths. The wasps will destroy moths at a rate of 10 moths per second when they are touching. 
Resolves #190
=> Hostile Flocks (Wasps)

Assets/Scripts/Lights/LightAttraction.cs, Assets/Scripts/Lights/LightController.cs, Assets/Scripts/Lights/LightData.cs
Adding a light attribute that makes them operate like anti-lights. The moths will be pushed away from them with a force proportional to the intensity of the light.
Resolves #216
=> Implementing Repulsive Lights

Assets/Scripts/GameController.cs
Pressing the spacebar key toggles the slow motion time. Slow motion is also disabled if the game is paused or the level is completed.
Resolves #224
=> Implementing slow motion control

Assets/Prefabs/Lights/Trap Light.prefab
=> Fixing trap light killing moths

Assets/Scripts/Lights/AutoPlayLevel.cs
Improving many aspects of the start screen page.
- I fixed the scale of the tilemap and shadow casters.
- Changed the name of the game
- Improved the code for the auto-play sequence
Resolves #237
=> Fixing start screen

Assets/Prefabs/UI/Menus/Decals.meta, Assets/Prefabs/UI/Menus/Decals/BottomDecal.prefab, Assets/Prefabs/UI/Menus/Decals/BottomDecal.prefab.meta, Assets/Prefabs/UI/Menus/Decals/TopDecal.prefab, Assets/Prefabs/UI/Menus/Decals/TopDecal.prefab.meta, Assets/Prefabs/UI/Menus/LevelFailedMenu.prefab, Assets/Prefabs/UI/Menus/LevelWonMenu.prefab, Assets/Prefabs/UI/Menus/MenuBase.prefab, Assets/Prefabs/UI/Menus/PauseMenu.prefab, Assets/Prefabs/UI/Menus/UIButton.prefab
I added some initial decals to the top and bottom of the menu base prefab. I like the bottom decal, but don't know how to create a pretty top-decal. If I could get some help from @TruestWaffle or @samanthamhill that would be great!
Resolves #239
=> Prettier menus

Assets/Audio/MusicMixer.mixer, Assets/Audio/MusicMixer.mixer.meta, Assets/Prefabs/Managers/AudioManager.prefab, Assets/Prefabs/UI/Menus/SettingsMenu.prefab, Assets/Scenes/LevelSelector.unity, Assets/Scripts/AudioManager.cs, Assets/Scripts/Menus/LevelSelectMenu.cs, Assets/Scripts/Menus/LevelSelectMenu.cs.meta, Assets/Scripts/Menus/SettingsMenu.cs
Many quality of life improvements to the sounds system in the game.
- Lowered the default sound on the main theme track.
- Added a settings menu page to the level selection scene. You can access the menu with the escape key.
- Split the volume mixer into two tracks for music and sound effects. I updated the settings menu to have two sliders to adjust the tracks independently. 
Resolves #252 
Resolves #254
=> Settings menu improvements

Assets/Prefabs/UI/Menus/PauseMenu.prefab, Assets/Prefabs/UI/Menus/SettingsMenu.prefab, Assets/Prefabs/UI/Menus/UIButton.prefab, Assets/Scripts/Menus/ButtonHover.cs, Assets/Scripts/Menus/ButtonHover.cs.meta
Improving the button hover effects for menus.
- The white box has that appears when you hover a button has been removed.
- The colour of the text now changes to a light green when the button is hovered.
- Decals were added to the sides of the buttons. The decals appear when the button is hovered.
- The spacing in the pause menu was fixed with a "Fit Contents" component.
- The hover sound effect was fixed.
Resolves #262 
Resolves #256 
Resolves #261
=> Button Hover Improvements

Assets/Prefabs/Lights/Point Lamp.prefab, Assets/Scenes/Levels/Level7.unity, Assets/Scripts/Lights/IntensityRange.cs, Assets/Scripts/Lights/LightRotation.cs
Fixed the "light leakage" problem that directional light had. Also replaced the old directional light in Level 7 with the new prefab instance.
Resolves #246
=> Fixed the directional light angle problem
